### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by shingz96** [rootm0s/WinPwnage#2]
i see the code seem still on python 2, correct me if i am wrong 

Thx :smiley:

**Comment by rootm0s** [comment]
That's correct, shouldn't be any problems converting it to python3 though

**Comment by rootm0s** [comment]
For those who want to run it with python3, ill suggest you have a look at:
https://docs.python.org/2/library/2to3.html

**Comment by cclauss** [comment]
[flake8](http://flake8.pycqa.org) testing of https://github.com/rootm0s/WinPwnage on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
/home/travis/virtualenv/python3.7.0/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
./winpwnage.py:6:9: E999 SyntaxError: invalid syntax
print """
        ^
./functions/todo/dll_oci.py:32:67: E999 SyntaxError: invalid syntax
	print " {} oci_dll_hijack: Attempting to dll hijack msdtc service".format(infoBox())
                                                                  ^
2     E999 SyntaxError: invalid syntax
2
```

**Comment by rootm0s** [comment]
Only supporting Python 2.7, if you want to try it out in Python 3, feel free to do all the work

**Comment by Abdur-rahmaanJ** [comment]
would like to contribute to py3 support!

**Comment by rootm0s** [comment]
This is on the [to-do list](https://github.com/rootm0s/WinPwnage/issues/19) list, closing the issue since it will be adressed in a future PR.
