### ISSUE TITLE
bypass uac - WSReset

### ISSUE THREAD

**Issue by AlessandroZ** [rootm0s/WinPwnage#20]
Hi, 

Here is another way for bypassing uac => https://www.activecyber.us/activelabs/windows-uac-bypass
I put it here to remember it, if you don't have time, I will take a look on it but right now, I have no time sorry :)

**Comment by rootm0s** [comment]
Nice, ill look into it! 👍

**Comment by rootm0s** [comment]
Just finished the function: [https://github.com/rootm0s/WinPwnage/blob/master/winpwnage/functions/uac/uac_wsreset.py](https://github.com/rootm0s/WinPwnage/blob/master/winpwnage/functions/uac/uac_wsreset.py)

I have no time to test on older versions of Windows 10, I tested on 1809/1803 and it works. Also tested on 1703 but it didn't work.

**Comment by rootm0s** [comment]
Closing issue, the function as been added.
