### ISSUE TITLE
error: bundle-files 1 not yet supported on win64

### ISSUE THREAD

**Issue by cclauss** [rootm0s/WinPwnage#28]
On Travis CI Windows environments, running __python build.py install__ raises:
___error: bundle-files 1 not yet supported on win64___

Is there a way to successfully complete the build process?

**Comment by rootm0s** [comment]
If you comment out the `"bundle_files": 1,` and change it to `"bundle_files": 3,` - It will compile on 64bit but it wont be a single executable, gonna have dependencies and dll files as well that is required.

**Comment by rootm0s** [comment]
There's no work-around that I know about, it's a py2exe limitation

**Comment by cclauss** [comment]
Makes sense.  Thx.
