### ISSUE TITLE
How this tool is use??

### ISSUE THREAD

**Issue by secfb** [rootm0s/WinPwnage#53]
I set it up.How this tool is used. There are no documents. Can you write a few examples?
![image](https://user-images.githubusercontent.com/38748801/59975259-1c717300-95bf-11e9-9d31-bd8b6edc8ae1.png)

**Comment by rootm0s** [comment]
If you want to scan the system for possible UAC bypasses, you pass these args:
`winpwnage.py --scan uac`

For example if you want to use "Fodhelper UAC bypass" you pass these arguments:
`winpwnage.py --use uac --id 2 --payload c:\\Windows\\system32\\cmd.exe`

**Comment by secfb** [comment]
thank you 👍🏻

**Comment by secfb** [comment]
I did not know that the tool should be installed on the target computer. This tool is useless if there is no internet on the target computer. I thought it could be used to upgrade the authorization after receiving the shell.

**Comment by rootm0s** [comment]
Well it depends on what you're going to use it for. The repo is to study the techniques so...

But for example:
It could be used to elevate malware without UAC showing up, or elevate from Administrator to System.
