### ISSUE TITLE
persis and techniques

### ISSUE THREAD

**Issue by moaeddy** [rootm0s/WinPwnage#54]
what are command for persistence and execution techniques?

**Comment by rootm0s** [comment]
Scan for possible persistence or execute techniques:
`winpwnage.py --scan persist`
`winpwnage.py --scan execute`

Add/remove persistence, using method 6.
`winpwnage.py --use persist --id 6 --payload c:\\windows\\notepad.exe --add`
`winpwnage.py --use persist --id 6 --payload c:\\windows\\notepad.exe --remove`

Execute techniques
`winpwnage.py --use execute --id 1 --payload c:\\windows\\notepad.exe`

**Comment by rootm0s** [comment]
Read the **winpwnage.py** file - If you understand Python, you'll understand how to use the tool.

**Comment by moaeddy** [comment]
i believe persistence was to make payload unkillable

**Comment by rootm0s** [comment]
Define unkillable 😂

**Comment by moaeddy** [comment]
you kill a process and it re-spawn unless boot into safemode before it can be undone

**Comment by rootm0s** [comment]
> you kill a process and it re-spawn unless boot into safemode before it can be undone

These methods only supports persistence between reboots (if safemode is activated, the payload is not executed on boot-up). This is basic knowlage when it comes to these simple methods.
