### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by kushal-17** [rootm0s/WinPwnage#56]
Can I get CASPER:socket based rat? As its been removed...

**Comment by rootm0s** [comment]
I removed long time ago, it's because I don't want people to do harm with it. It was only for educational purpose only and to test on your own enviroment.

**Comment by kushal-17** [comment]
Sir is there any chance to get that please. Don't want to harm but for
educational purpose as I m student of computer engineering please if you
provide it will be helpful to me.🥺
