### ISSUE TITLE
Error using the payload example you mentioned in the other issue

### ISSUE THREAD

**Issue by thelegendman2** [rootm0s/WinPwnage#58]
title
![2e8fbafb771c7ac4749db7623d27d7fa](https://user-images.githubusercontent.com/26191965/67719664-28849b80-f9ca-11e9-8f8a-f12edeca8915.png)

**Comment by thelegendman2** [comment]
Actually ive just seen it requires a dll payload my mistake

**Comment by rootm0s** [comment]
No worries :)
