### ISSUE TITLE
detected by antivirus

### ISSUE THREAD

**Issue by ZerOne-Byte** [rootm0s/WinPwnage#68]
This tool is detected by antivirus
how can i encoding this tool for anti detect?

**Comment by ZerOne-Byte** [comment]
windows Defender
And I think other antiviruses will detect it

**Comment by rootm0s** [comment]
It works fine here with Windows Defender. What pyinstaller params are you using? `--noconsole` param is known to make the executable detectable.

**Comment by byehack** [comment]
> This tool is detected by antivirus
> how can i encoding this tool for anti detect?

this problem is not from this project :/

**Comment by rootm0s** [comment]
> > This tool is detected by antivirus
> > how can i encoding this tool for anti detect?
> 
> this problem is not from this project :/

That's true, but on my side, Windows Defender never complains, so not sure how it's detected on your side. 

However, it might be a fun challenge to implement some tricks to bypass AVs in the future 👍
