### ISSUE TITLE
Specify which methods support executable with parameters in methods info.

### ISSUE THREAD

**Issue by byehack** [rootm0s/WinPwnage#71]
for example `persistMethod4` doesn't support using exe with params.
but `persistMethod5` and `persistMethod6` supports exe with params.

**Comment by rootm0s** [comment]
> for example `persistMethod4` doesn't support using exe with para

Do you mean that the method itself does not support params? It works fine here, it creates registry value: `C:\WINDOWS\system32\userinit.exe,c:\\windows\\system32\\cmd.exe /c calc.exe`

**Comment by byehack** [comment]
> It works fine here, it creates registry value: `C:\WINDOWS\system32\userinit.exe,c:\\windows\\system32\\cmd.exe /c calc.exe`

is it starts calculator after restart windows?

**Comment by rootm0s** [comment]
I had troubles with the calc, it did not work after restart but changed to: `C:\WINDOWS\system32\userinit.exe,c:\\windows\\system32\\cmd.exe /c mspaint.exe` and it runs after reboot

**Comment by byehack** [comment]
so good. but i think all of the uac/persist/evelate doesn't support params.

**Comment by rootm0s** [comment]
Then test all of them and write a sum-up. The functions has been tested already, so they all should work.
