### ISSUE TITLE
question??

### ISSUE THREAD

**Issue by powerhellman** [rootm0s/WinPwnage#75]
can i ask for some help with modifying something?

**Comment by rootm0s** [comment]
It depends on what you want to change

**Comment by powerhellman** [comment]
Well since im not that good at codinf i was wonderig if you could make a
custom version where it runs a specific payload on each uac module
eventually hitting one giving the command admin. Pls :)

**Comment by rootm0s** [comment]
There's already support for that. But you need some coding experience to figure it out I guess.

**Comment by powerhellman** [comment]
Well i kinda already did it with like the same command repeated 15 times on
differant uac modules. But i need something i bit more compact pls.
U are much more skilled than me :)

**Comment by rootm0s** [comment]
I dont have time to assist you with that

**Comment by powerhellman** [comment]
Oh rlly ok :( well what you do is amazing and keep uo the good work :)

**Comment by jschlob** [comment]
Sure

**Comment by jschlob** [comment]
Sure what is it?
