### ISSUE TITLE
is 20!????

### ISSUE THREAD

**Issue by powerhellman** [rootm0s/WinPwnage#77]
![Screenshot_20201108-222113_Firefox](https://user-images.githubusercontent.com/73621616/98496957-ced7c380-2210-11eb-903a-c79d5df02bbf.jpg)

**Comment by powerhellman** [comment]
When was there a id 20?

**Comment by rootm0s** [comment]
Back when we had support for DLL based UAC bypasses. They got removed a while back and I forgot got update the blog post.

The new ID for wsreset is:
https://github.com/rootm0s/WinPwnage/blob/master/winpwnage/functions/uac/uacMethod14.py
