### ISSUE TITLE
when multiple bypasses are used in the same script

### ISSUE THREAD

**Issue by nubonics** [rootm0s/WinPwnage#82]
so instead of using the cli, im using python code

i can successfully bypass a single executable, but I cant bypass two within the same script which makes me believe [without looking at the code] that there code that is telling it to exit, as python code does not normally exit the script without the dev specifically telling it to do so, so I am kinda wondering about this
this project is awesome! btw :D
```
from time import sleep
from winpwnage.functions.uac.uacMethod4 import uacMethod4


f1 = r"C:\Users\nubonix\sandboxie\sandboxie.exe"
f2 = r"C:\Users\nubonix\Desktop\WinPwnage\dist\cli\cli.exe"
uacMethod4([f1])
sleep(30)  # after various re-trials of trying to get more than one executable to be bypassed within the same script/program, this was my sanity check
uacMethod4([f2])

```

**Comment by rootm0s** [comment]
There's no exit within each module, so it's not that if you're importing it like you do in the example.

I don't have a test machine ready so can't test it out fully. Do you get any stdout at all?

**Comment by nubonics** [comment]
Yes, i get output for the first execution, but right after the first bypass / execution happens, the script terminates.

Here is an example: [installing sandboxie on a computer without running an admin prompt]
the first line starts the sandboxie_setup.exe
the second line starts the python script i wrote and converted into an exe [installs sandboxie using pywinauto]
`
from winpwnage.functions.uac.uacMethod4 import uacMethod4

uacMethod4([ r"C:\Users\nubonix\AppData\Local\NBM\NBM\data\downloads\sandboxie\sandboxie.exe"])
uacMethod4([r"C:\Users\nubonix\Desktop\WinPwnage\dist\install_sandboxie.exe"])
`

I can provide any additional information

**Comment by rootm0s** [comment]
I tested this out, with multiple UAC bypasses in the same script and it's working fine while using uacMethod1 (which is basicly win api, runas function).

This behavior is most likely caused by the uacMethod4 itself or AVs.

```python
from winpwnage.functions.uac.uacMethod1 import uacMethod1

uacMethod1(r"c:\windows\notepad.exe")
uacMethod1(r"c:\windows\system32\mspaint.exe")
```

**Comment by nubonics** [comment]
hmm, alright, now sure what you mean by cleanup, but I will try the other uac methods.
Thank you :)

**Comment by rootm0s** [comment]
In your example, the method did not perform this function. Which indicates something made it stop before executing this function.

```python
def uacMethod4_cleanup(path):
	print_info("Performing cleaning")
	if registry().remove_key(hkey="hkcu", path=path, name="windir", delete_key=False):
		print_success("Successfully cleaned up")
	else:
		print_error("Unable to cleanup")
		return False
```
