### ISSUE TITLE
UAC Bypass #4 - No Behavior

### ISSUE THREAD

**Issue by dekrypted** [rootm0s/WinPwnage#89]
I tried using UAC bypass 4. Intitially, it said it could not find the schtasks executable. To fix this, I used os.system instead of the process method you made. Still, all that happens is you see a working cursor. No payload is spawned.

**Comment by rootm0s** [comment]
Sounds like the execution-flow is interrupted by Anti-Malware like Windows Defender. I tested method 4 and it's working on all my virtual Windows machines.

**Comment by dekrypted** [comment]
Okay... I'll keep you posted!
